"""U13 Isolation and Promotion subsystem."""

from v7_harness.isolation.errors import (
    AlternateDataStreamError,
    CaseAliasError,
    ConcurrentOwnershipError,
    ExternalWriteDetectedError,
    GitWorktreeError,
    IsolationError,
    LiveMutationProhibitedError,
    PatchHashMismatchError,
    PathOutsideRootError,
    PathSecurityError,
    PathTraversalError,
    ReparsePointError,
    ScopeExpansionError,
    SourceDivergenceError,
    SourceMutationError,
    StaleFenceOrReceiptError,
    UncPathError,
    UnresolvedEffectError,
    UntrackedOverwriteError,
    WatchScanUnavailableError,
)
from v7_harness.isolation.git_worktree import (
    GitWorktreeAdapter,
    GitWorktreeContext,
)
from v7_harness.isolation.manifest import (
    DeterministicManifest,
    ManifestEntry,
    PatchBundle,
    PatchItem,
    build_manifest,
    compute_bundle_id,
    create_patch_bundle,
)
from v7_harness.isolation.promotion import (
    PromotionDryRunResult,
    apply_promotion,
    dry_run_promotion,
)
from v7_harness.isolation.security import (
    WatchRootsSnapshot,
    assert_no_reparse_or_symlink,
    check_case_alias_set,
    check_case_match_on_disk,
    check_scope_confinement,
    is_symlink_or_reparse,
    snapshot_watch_roots,
    validate_canonical_path_in_root,
    validate_safe_relative_path,
)
from v7_harness.isolation.staging import (
    NonGitStagingAdapter,
    StagingWorkspace,
)

__all__ = [
    "AlternateDataStreamError",
    "CaseAliasError",
    "ConcurrentOwnershipError",
    "DeterministicManifest",
    "ExternalWriteDetectedError",
    "GitWorktreeAdapter",
    "GitWorktreeContext",
    "GitWorktreeError",
    "IsolationError",
    "LiveMutationProhibitedError",
    "ManifestEntry",
    "NonGitStagingAdapter",
    "PatchBundle",
    "PatchHashMismatchError",
    "PatchItem",
    "PathOutsideRootError",
    "PathSecurityError",
    "PathTraversalError",
    "PromotionDryRunResult",
    "ReparsePointError",
    "ScopeExpansionError",
    "SourceDivergenceError",
    "SourceMutationError",
    "StagingWorkspace",
    "StaleFenceOrReceiptError",
    "UncPathError",
    "UnresolvedEffectError",
    "UntrackedOverwriteError",
    "WatchScanUnavailableError",
    "apply_promotion",
    "assert_no_reparse_or_symlink",
    "build_manifest",
    "check_case_alias_set",
    "check_case_match_on_disk",
    "check_scope_confinement",
    "compute_bundle_id",
    "create_patch_bundle",
    "dry_run_promotion",
    "is_symlink_or_reparse",
    "snapshot_watch_roots",
    "validate_canonical_path_in_root",
    "validate_safe_relative_path",
]
